SET-317: implement commit retrieval
jboss-set/aphrodite pull request #238
Opened 2020-12-09 17:25 UTC by michpetrov

Issue: [SET-317](https://projects.engineering.redhat.com/browse/SET-317)

Adding a method to retrieve a list of commits from a repo, needed to check if a PR has been merged into a given branch.

2020-12-11 06:18 UTC, baranowb requested changes

2020-12-14 12:19 UTC, michpetrov commented on domain/src/main/java/org/jboss/set/aphrodite/domain/Commit.java
> +/*
PullRequest keeps a List<String> of commits, do you want to change that to Commit? I haven't found other uses.

2021-01-28 11:12 UTC, michpetrov commented
@baranowb waiting on your feedback.

2021-02-02 09:27 UTC, baranowb commented
@michpetrov  and you shall receive it!

2021-02-02 09:42 UTC, baranowb commented on domain/src/main/java/org/jboss/set/aphrodite/domain/Commit.java
> +/*
yes, either way. It needs to be the same in both, either one version or another.

2021-02-02 16:11 UTC, michpetrov commented
@baranowb updated and rebased

2021-02-03 05:56 UTC, merged