SET-556: retrieve a list of new issues since a given date
jboss-set/aphrodite pull request #264
Opened 2023-01-30 18:32 UTC by michpetrov

Issue: [SET-556](https://issues.redhat.com/browse/SET-556)

This is mostly intended to be used after we get the list of all issues in a payload, so we can find out which are new. The search API doesn't let us retrieve the changelog (well the API does, the client doesn't have it implemented), so we have to make a separate request.

2023-02-21 11:49 UTC, baranowb requested changes

2023-02-21 11:56 UTC, michpetrov commented on jira/src/main/java/org/jboss/set/aphrodite/issue/trackers/jira/JiraRelease.java
> +    public List<Issue> getNewIssues(LocalDate since) throws NameNotFoundException {
new "means new on the payload", i.e. any issue that had the fixVersion changed to the version of the release since a given date

2023-02-21 12:50 UTC, michpetrov commented on jira/src/main/java/org/jboss/set/aphrodite/issue/trackers/jira/JiraIssueTracker.java
> +    public List<Issue> getIssuesAddedSince(Version version, LocalDate since) {
I'm not sure I understand what startDate and endDate would mean if I made it like that

Do you want to this to get issues that had the version added since startDate but have a different version since endDate? Or issues that had the version added since startDate without the issues that had it added after endDate?

The current JIRA query is `fixVersion = X AND fixVersion was not X BEFORE YYYY-MM-DD` so it's already kinda confusing.

2023-02-21 12:51 UTC, michpetrov commented on jira/src/main/java/org/jboss/set/aphrodite/issue/trackers/jira/JiraIssueTracker.java
> +                .setProduct("JBEAP")
The method right above it has it hardcoded too, but sure I can change that

2023-02-23 11:08 UTC, michpetrov commented on jira/src/main/java/org/jboss/set/aphrodite/issue/trackers/jira/JiraIssueTracker.java
> +    public List<Issue> getIssuesAddedSince(Version version, LocalDate since) {
@baranowb ^

2023-02-24 07:43 UTC, baranowb commented on jira/src/main/java/org/jboss/set/aphrodite/issue/trackers/jira/JiraRelease.java
> +    public List<Issue> getNewIssues(LocalDate since) throws NameNotFoundException {
Ok, given that its in JIRA release it kind of makes sense. Otherwise it would set expectations on result that is not clearly defined by method name.

2023-02-24 07:43 UTC, baranowb commented on jira/src/main/java/org/jboss/set/aphrodite/issue/trackers/jira/JiraIssueTracker.java
> +                .setProduct("JBEAP")
https://github.com/jboss-set/aphrodite/blob/d8b5082a808b75dbda386824f0ffdb0070b5833d/jira/src/main/java/org/jboss/set/aphrodite/issue/trackers/jira/JiraRelease.java#L47

2023-02-24 07:58 UTC, baranowb commented on jira/src/main/java/org/jboss/set/aphrodite/issue/trackers/jira/JiraIssueTracker.java
> +    public List<Issue> getIssuesAddedSince(Version version, LocalDate since) {
hmm so Id say change method name is .getIssuesAddedToVersion ? Makes it more version centric as its the bigger factor.
What I have in mind is getIssuesAddedToVersion(Version v, Date since, Date to)  -  this would allow us to get more taylored result which is useful in case of sort of bisecting results.
getIssuesAddedToVersion(v,since,null) would do above.

2023-02-27 11:18 UTC, michpetrov commented
@baranowb rebased

2023-03-06 07:20 UTC, baranowb commented
+1

2023-03-06 14:20 UTC, merged